language: cpp
compiler:
  - clang
before_script:
  - apt-cache show libboost-dev libboost-graph1.46.1 libboost-graph1.46-dev libqt4-dev qt4-qmake
  - sudo apt-get install libboost-dev libboost-graph1.46.1 libboost-graph1.46-dev libqt4-dev qt4-qmake
